solve issue #29 (from tcatm): don't bail out without nl80211
freifunk-gluon/l3roamd pull request #1
Opened 2017-02-16 18:21 UTC by matwei

With this change the program just prints an error message when
there is no support for nl80211 in the kernel.

To work properly it is checked wether ctx->wifistations_ctx.fd is
initialized (!= 0) before polling at this file descriptor in
function loop().

2017-02-16 20:14 UTC, neocturne requested changes

2017-02-16 20:14 UTC, NeoRaider commented on src/wifistations.c
> +		ctx->nl_sock = NULL;
`ctx->fd` should be set to -1 here, as 0 is a valid file descriptor.

2017-02-16 20:14 UTC, NeoRaider commented on src/main.c
> +	if (ctx->wifistations_ctx.fd) {
Make this check:
```
if (ctx->wifistations_ctx.fd >= 0)
```

2017-02-16 20:14 UTC, NeoRaider commented on src/main.c
> +				  && ctx->wifistations_ctx.fd == events[i].data.fd) {
This change is not necessary, `events[i].data.fd` will never match `ctx->wifistations_ctx.fd` if `ctx->wifistations_ctx.fd` is not a valid file descriptor.

2017-02-19 11:46 UTC, matwei commented on src/wifistations.c
> +		ctx->nl_sock = NULL;
You're right, I changed this.

Initially I left it untouched because it wasn't modified in the function at that point.

2017-02-19 11:50 UTC, matwei commented on src/main.c
> +	if (ctx->wifistations_ctx.fd) {
Changed as you recommended

2017-02-19 11:51 UTC, matwei commented on src/main.c
> +				  && ctx->wifistations_ctx.fd == events[i].data.fd) {
Removed the change.

2017-02-19 11:53 UTC, matwei commented
I addressed the comments from @NeoRaider in Version  3b146ba

2017-02-21 08:25 UTC, neocturne approved these changes

2017-02-21 08:26 UTC, merged